name: test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: step1
        run: echo " Step 1 done"

      - name: step2
        run: echo "YOOOO" > test.txt
      - name: step3
        run: cat test.txt
